---
default:
  target: default
  outputs:
    default:
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DBT_DATABRICKS_SCHEMA') }}"
      threads: 6
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      type: databricks
